workflows:
  default:
    name: Quick Games iOS Build
    max_build_duration: 60
    
    environment:
      xcode: latest

    scripts:
      - name: Build iOS App
        script: |
          xcodebuild build \
            -workspace QuickGames.xcworkspace \
            -scheme QuickGames \
            -configuration Release \
            -derivedDataPath build/ios_build

    artifacts:
      - build/ios_build/Build/Products/Release-iphoneos/*.app
